title: Mark Egge # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Transportation data derring-doer @ High Street. 
  <br><br>
  Providing high-octane data analytics to the agencies that build and operate America’s transportation networks.
  <br><br>
  <a href="https://www.linkedin.com/in/markegge/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-GMXDD7KL1E # your Google Analytics tracking ID here